generalMoveNames = {
    "jab": "Jab",
    "jab1": "Jab 1",
    "jab2": "Jab 2",
    "jab3": "Jab 3",
    "rapidjabs_start": "Rapidjabs Start",
    "rapidjabs_loop": "Rapidjabs Loop",
    "rapidjabs_end": "Rapidjabs End",
    "dashattack": "Dash Attack",
    "ftilt": "Foward Tilt",
    "ftilt_h": "Angled Up",
    "ftilt_mh": "Angled Mid/Up",
    "ftilt_m": "Angled Mid",
    "ftilt_ml": "Angled Mid/Down",
    "ftilt_l": "Angled Down",
    "utilt": "Up Tilt",
    "dtilt": "Down Tilt",
    "fsmash": "Forward Smash",
    "fsmash_h": "Angled Up",
    "fsmash_mh": "Angled Mid/Up",
    "fsmash_m": "Angled Mid",
    "fsmash_ml": "Angled Mid/Down",
    "fsmash_l": "Angled Down",
    "usmash": "Up Smash",
    "dsmash": "Down Smash",
    "nair": "Neutral Air",
    "fair": "Forward Air",
    "bair": "Back Air",
    "uair": "Up Air",
    "dair": "Down Air",
    "grab": "Grab",
    "dashgrab": "Dash Grab",
    "pummel": "Pummel",
    "fthrow": "Forward Throw",
    "bthrow": "Back Throw",
    "uthrow": "Up Throw",
    "dthrow": "Down Throw",
    "nspecial": "Neutral Special",
    "sspecial": "Side Special",
    "uspecial": "Up Special",
    "dspecial": "Down Special"
}
